update

diff --git a/.github/workflows/cross-env.yaml b/.github/workflows/cross-env.yaml
--- a/.github/workflows/cross-env.yaml
+++ b/.github/workflows/cross-env.yaml
@@ -24,6 +24,12 @@ jobs:
       image: mcr.microsoft.com/playwright:v1.47.2-jammy
 
     steps:
+      - name: Validate secrets
+        if: ${{ !env.BASE_URL_WEB }}
+        run: |
+          echo "::error::BASE_URL_WEB is not set!"
+          exit 1
+          
       - uses: actions/checkout@v4
 
       - uses: actions/setup-node@v4
@@ -39,7 +45,7 @@ jobs:
           HOME: /root
           USER:  ${{ env.USER }}
           PASSWORD: ${{ secrets.PASSWORD }}
-          BASE_URL_WEB: ${{ secrets.BASE_URL_WEB }} 
+          BASE_URL_WEB: ${{ env.BASE_URL_WEB }} 
           BASE_URL_API: ${{ env.BASE_URL_API }}
 
       - name: Run Playwright tests
